# Generated by Django 4.1.7 on 2023-04-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.IntegerField(max_length=11)),
                ('email', models.CharField(max_length=40)),
                ('contato', models.IntegerField(max_length=40)),
            ],
        ),
    ]
