# Generated by Django 4.1.7 on 2023-04-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME', models.CharField(max_length=100)),
                ('QUANTIDADE', models.IntegerField(max_length=11)),
                ('EMAIL', models.CharField(max_length=40)),
                ('CONTATO', models.IntegerField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='contato',
            new_name='CONTATO',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cpf',
            new_name='CPF',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='email',
            new_name='EMAIL',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='name',
            new_name='NOME',
        ),
    ]
